### ISSUE TITLE
Commit relacionado a dois tópicos

### ISSUE THREAD

**Issue by LuccaPrado** [douglasfernandesjr/papSpringBoot#1]
Olá, gostaria de saber qual a melhor forma para commitar algo que seja de dois tópicos diferentes, pois queria publicar uma forma de consumir o swagger mesmo estando autenticado

**Comment by douglasfernandesjr** [comment]
Coloca como um passo 4 aqui: https://github.com/douglasfernandesjr/papSpringBoot/wiki/06_restsecurity,
no passo 2 é adicionada a configuração para permitir o acesso anonimo ao swagger.

**Comment by douglasfernandesjr** [comment]
wiki será refatorada.
